# Generated by Django 3.2.8 on 2021-11-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_pic',
            name='image_filled',
            field=models.BooleanField(default=False),
        ),
    ]
