# Generated by Django 3.2.8 on 2021-11-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courses_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
